perf: Improve performance for migration (#2898)
* improve performance for migration

* increase iterator chunk_size for migration

* fix error applying migration 0031_update_schema_after_pyxform_upgrade

fix TypeError: UseMaster.__call__() missing 1 required positional argument: 'func'

* update log message for migration

* refactor to use use_master decorator

* unpin migration to master db

migrations are run against the default db, hence the use_master decorator is unnecessary

* fix typo

* catch TypeError when regenerating XForm schema from file