fix error when creating user with no password
fix AttributeError: 'NoneType' object has no attribute 'lower' when creating a user with password field missing from the payload