fix ModuleNotFoundError: No module named 'pkg_resources
ModuleNotFoundError: No module named 'pkg_resources' thrown when installing via git. pkg_resources is deprecated and scheduled for removal in setuptools 81.