fix error applying migration 0031_update_schema_after_pyxform_upgrade
fix TypeError: UseMaster.__call__() missing 1 required positional argument: 'func'