Add support for entities (#2504)
* add entities models

add EntityList, RegistrationForm, FollowUpForms models
add tests
upgrade pyxform

* add support for publishing xlsform w/entities

* fix typo in docstring

* handle replacing a form with entities definition

* create entities FollowUpForm on publish

On publish, we check if a form references a dataset that is an EntityList and create a FollowUpForm object

* add test case

* add fields version,json to RegistrationForm

* add model Entity

* save registration form json when creating xform

* refactor code

* update docstring

* delete whitespace

* add field version to model Entity

* update doc string

* update doc string

* disable registration form if form is replaced with no entities definition

* refactor code

* refactor code

* recreate migrations

* add test cases

* fix typo

* disable previous RegistrationForm if XLSForm entities list_name changes

* add test case

* refactor tests

* enhance test case

* suppress lint error

suppress imported but unused error

* refactor code

* fix cyclic-import lint error

* add code comment

* rename related name follow_up_lis to follow_up_forms

* create entity on submission

* create followup form MetaData on publish

* fix lint error

fix reimported / Reimport 'MetaData'

* add is_active field to model FollowUpForm

* add support for downloading entity list dataset

* refactor code

* address lint errors

address wrong-import-order and line-too-long

* add endpoint api/v1/entity-lists

* add test case

* suppress lint error

suppress lint error too-many-ancestors

* fix failing tests

* add test cases

* add test case

* fix failing test

* save Entity json properties as alias

when creating an Entity, replace the fieldname with  alias defined in the XLSForm

* address lint error

address pylint: too-many-lines

* update comment

* suppress lint error too-many-lines

* add endpoint to GET Entities

add endpoint /api/v1/entity-lists/<entity_list_id>/entities

* optimize performance

* reduce migrations

* add code comments

* remove unrelated changes in migration

* use raw string for entity-list url

* add attribute to get dataset properties from an EntityList object

* export EntityList dataset with the appropriate headers

* refactor code

* fix lint error

fix error variable 'tagName' in function should be lowercase

* replace  xml.dom.minidom.parseString with defusedxml.minidom.parseString

avoid XML attacks by using defusedxml equivalent https://pypi.org/project/defusedxml/#defusedxml-sax

* fix bug 'types.UnionType' object has no attribute 'properties'

* address failing test

* fix failing tets

* fix failing tests

* always create new export for entity list dataset

* refactor code

* add model GenericExport

add model GenericExport that will store data for Entity datasets exports and any other generic export

* address lint errors

* address lint error Redefining built-in 'object'

* fix bug entity dataset export not created

* rename methods

* fix bug invalid method call

* update entity dataset hash on new submission

* suppress lint error import-outside-toplevel

* fix pylint error

fix pylint error cyclic-import / Cyclic import (onadata.apps.logger.models.entity -> onadata.apps.logger.models.registration_form -> onadata.apps.logger.models.entity_list)

* suppress lint error

suppress error pylint: invalid-name / Variable name "Entity" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (col

* ignore flake8 warning

ignore warning N806 / variable 'Entity' in function should be lowercase

* optimize xform manifest hash recalculation for entity datasets

* fix lint warning invalid-name

* suppress lint warninng

* update docstrings

* add tests

* update docstring

* fix typo in comment

* enhance docstring

* handle some edge cases

* fix typo

* update code comment

* add task to persist cached entities data to database

* suppress lint warning invalid-name

* suppress lint warning invalid-name

* add num_entities in api/v1/entity-list response

add num_entities in the response that returns how many entities an EntityList dataset has

* refactor code

* add EntityList property queried_num_entities

* rename EntityList property current_last_update_time

* update code comment

* update docstring

* exclude db query from EntityList last entity update time

* fix failing tests

* fix failing test

* include which EntityList a form contributes to when get list of forms and a single form

* add to form list and form responses the EntityLists form consumes Entities

* fix failing test

* readd attribute is_instance_json_regenerated

* fix failing tests

* add support to filter EntityLists by project id

* add fields to forms exposed on endpoint /api/v1/projects

* fix error NotImplementedError: .filter_queryset() must be overridden.

* add created_at, updated_at to list of EntityLists endpoint

* add _id to response at endpoint /api/v1/entity-lists/<id>/entities

* fix failing test

* remove EntityList num of entities cache increment

when committing the cache increment to the DB, we cannot guarantee the operation is going to atomic. We have to clear the key from cache and at that same moment, the cache value can be in the process of being updated

* fix migration conflict

* fix failing tests

* fix failing tests

* fix failing tests

* fix failing tests

* fix failing tests

* refactor to publish forms in markdown

* make use of existing base model

* squash entities migrations

* create XFormversion when publish markdown during test runs

* refactor TestBase

* refactor tests

* refactor tests

* fix failing tests

* fix failing tests

* fix method resolution order error

* fix failing tests

* refactor code

* remove superflous code

* add attributes login_username, login_password to TestAbstractViewSet

* fix failing tests

* add documentation for Entities

* address grammartical error

* update entities documentation

* remove unused model methods

* ignore deleted Entities when getting Entities

* refactor code

* refactor code

* refactor code

* refactor code

* refactor code

* remove entity migrations

* re-make entities migration

* move entities endpoints to v2

* update entities documenatation

* address failing test

* add a reverse_code argument for migration 0014_populate_attachment_xform

This resolves the error django.db.migrations.exceptions.IrreversibleError when unapplying the migration

* resolve typo

* add doc string