Fix stale data sent to rest services after editing submission (#2667)
* fix stale data sent to rest services when editing submission

The data sent to rest services can be stale if the instance is not yet saved to the database when a submission is edited

* pin to master

* add comment

* fix typo in comment

* Wait for transaction to complete before calling webhooks (#2675)

* wait for transaction to complete before calling webhooks

* refactor code

* refactor code

* fix exception

fix exception AttributeError: 'ParsedInstance' object has no attribute 'xform'

* fix failing tests

capture on commit callbacks

* move misplaced comment

* use master database when calling external services

Call webhooks is a second-effect of creating/updating a submission. The operation should be pinned to master database, so that the replicas can be used by the clients reading from the API

* fix failing tests

* fix failing tests